config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :avatars do
    get :login
  end
  devise_for :users

  root controller: :avatars, action: :index

  get 'lobby', controller: :lobby, action: :index
  post 'lobby/message', controller: :lobby, action: :message
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :room, class_name: 'Room'
  belongs_to :global_actor, polymorphic: true

  validates_presence_of :room, :token
  validates :token, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user
  belongs_to :job, class_name: 'Job'

  validates_presence_of :user, :job, :level, :experience

  has_one :actor, as: :global_actor, dependent: :destroy
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :avatars, class_name: 'Avatar'
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :actors, as: :global_actor, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :outgoing_connections,
           class_name: 'RoomConnection',
           join_table: :room_connections,
           foreign_key: :room_from_id

  has_many :incoming_connections,
           class_name: 'RoomConnection',
           join_table: :room_connections,
           foreign_key: :room_to_id

  has_many :actors, class_name: 'Actor'

  def introduction
    other_players = actors.where(global_actor_type: 'Avatar').size - 1

    if other_players.positive?
      response = description + "<br /> There #{other_players > 1 ? 'are' : 'is'} #{other_players.humanize} other player#{other_players > 1 ? 's' : ''} in the room."
    else
      response = description
    end

    if outgoing_connections.present?
      response += "<br /> You see #{outgoing_connections.size} exit(s): #{outgoing_connections.collect{|c| c.command}.join(', ')}"
    end

    response
  end
end

app/models/room_connection.rb
class RoomConnection < ApplicationRecord
  belongs_to :room_from, class_name: 'Room'
  belongs_to :room_to, class_name: 'Room'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true

  has_many :avatars, class_name: 'Avatar', dependent: :destroy

  def gravatar_url
    gravatar_id = Digest::MD5.hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end

  def channel_token
    Digest::MD5.hexdigest(username).downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def index
    @avatars = current_user.avatars
  end

  def new
    @avatar = Avatar.new
  end

  def show
    @avatar = Avatar.find(params[:id])
  end

  def create
    @avatar = Avatar.new permitted_parameters
    @avatar.user_id = current_user.id

    @avatar.level = 1
    @avatar.experience = 0

    if @avatar.save
      flash[:success] = "Avatar #{@avatar.name} was created successfully"
      redirect_to avatars_path
    else
      render :new
    end
  end

  def login
    @avatar = Avatar.find(params[:avatar_id])

    actor = Actor.find_by(global_actor_id: @avatar.id, global_actor_type: 'Avatar')
    if actor.nil?
      actor = Actor.create(
        room_id: 1,
        global_actor_id: @avatar.id,
        token: SecureRandom.hex(10),
        global_actor_type: 'Avatar'
      )
    end

    session[:actor_id] = actor.id

    redirect_to '/lobby'
  end

  protected

  def permitted_parameters
    params.require(:avatar).permit(:name, :job_id)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
end

app/controllers/lobby_controller.rb
class LobbyController < ApplicationController
  before_action :ensure_actor
  skip_before_action :verify_authenticity_token

  def index
    @actor = Actor.find(session[:actor_id])
  end

  def message
    @message = params.dig(:message)
    @actor = Actor.find_by(token: params.dig(:room_id))

    @actor.room.actors.where(global_actor_type: 'Avatar').each do |actor|
      RoomChannel.broadcast_to actor.token, {
        message: @message, username: @actor.global_actor.name,
        updated_at: Time.now.strftime('%H:%M:%S')
      }
    end

    render json: { success: true }
  end

  protected

  def ensure_actor
    if session[:actor_id].blank?
      redirect_to '/avatars', flash: { danger: 'Please select an avatar.' }
    end
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)

    RoomChannel.broadcast_to @room, @room_message
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    url = "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/avatars/_avatars.html.erb
<% if @avatars.present? %>
  <nav class="nav flex-column">
    <% @avatars.each do |avatar| %>
      <%= link_to avatar.name, avatar_path(avatar), class: 'nav-link avatar-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    <ul style="list-style-type: none; padding-left: 20px;"><li>You have no avatars</li></ul>
  </div>
<% end %>

<div class="mb-3">
  <%= link_to new_avatar_path, class: 'btn btn-primary' do %>
    Create an avatar
  <% end %>
</div>

app/views/avatars/_form.html.erb
<div class="row no-gutters avatars__create">
  <div class="col">
    <div class="avatars__create--item js-avatar-selection" data-job-id="1" style="background-image: url(<%= asset_path('warrior.jpg') %>);">
      <h1>Warrior</h1>
    </div>
  </div>
  <div class="col">
    <div class="avatars__create--item js-avatar-selection" data-job-id="2" style="background-image: url(<%= asset_path('mage.jpg') %>);">
      <h1>Mage</h1>
    </div>
  </div>
  <div class="col">
    <div class="avatars__create--item js-avatar-selection" data-job-id="3" style="background-image: url(<%= asset_path('paladin.jpg') %>);">
      <h1>Paladin</h1>
    </div>
  </div>
  <div class="col">
    <div class="avatars__create--item js-avatar-selection" data-job-id="4" style="background-image: url(<%= asset_path('druid.jpg') %>);">
      <h1>Druid</h1>
    </div>
  </div>
</div>

<div id="avatarModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createAvatarModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <%= simple_form_for @avatar do |form| %>
        <%= form.hidden_field :job_id %>
        <%= form.input :name %>
        <%= form.submit "Create", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/avatars/index.html.erb
<div class="my-3">
  <h4 class="alert-heading text-center">Please Select an Avatar!</h4>

  <div class="row">
    <div class="col-12 col-md-3">
      <div class="avatars__sidebar">
        <%= render partial: 'avatars' %>
      </div>
    </div>

    <div class="col">
      <!-- <div class="alert alert-primary">
        <h4 class="alert-heading text-center">
          Please Select an Avatar!
        </h4>
      </div> -->
    </div>
  </div>
</div>

app/views/avatars/new.html.erb
<%= render partial: 'form' %>

app/views/avatars/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="jumbotron">
        <h1><%= @avatar.name %></h1>

        <strong><%= @avatar.job.name %></strong><br />
        <strong>Level: </strong> <span class="badge badge-primary"><%= @avatar.level %></span><br />
        <strong>Experience: </strong> <span class="badge badge-primary"><%= @avatar.experience %></span>
      </div>

      <%= link_to avatar_login_path(@avatar), class: 'btn btn-primary' do %>
        Login
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMUD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'shared/navigation_bar' %>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Log In / Sign Up</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'shared/navigation_bar' %>
    <div class="splash">
      <video autoplay muted loop id="myVideo">
        <source src="/assets/forest.mp4" type="video/mp4">
      </video>
      <div class="container">
        <div class="row">
          <div class="col-12 col-valign-middle">
            <div class="my-3">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/lobby/index.html.erb
<div class="chat d-flex align-items-end" data-channel-subscribe="room" data-room-id="<%= @actor.token %>">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text">[<%= Time.now.strftime('%H:%M:%S') %>] <%= @actor.room.introduction.html_safe %></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="input-group mb-3">
  <%= text_field :message, :message, {
    class: 'chat-input',
    style: 'width: 90%'
  } %>
  <div class="input-group-append">
    <%= submit_tag "Send", class: 'btn btn-primary chat-input' %>
  </div>
</div>



<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the RailsChatTutorial!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room  
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>

<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="gravatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href="/">RailsMUD</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="gravatar" src="<%= current_user.gravatar_url %>">
        <%= current_user.username %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>
</nav>
<% if flash.present? %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
<% end %>